async function api(url, options={}){const r=await fetch(url,{...options,headers:{'Accept':'application/json',...(options.headers||{})}});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail||'Request failed');return data}
function bindAuth(id,url,redirect){document.getElementById(id).addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;const err=document.getElementById('formError');err.textContent='';const body=Object.fromEntries(new FormData(f));try{await api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});location.href=redirect}catch(x){err.textContent=x.message}})}
async function logout(){await api('/api/logout',{method:'POST'});location.href='/'}
function money(v){return '₹'+Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}
function renderResult(r){let html=`<div class="success">✓ Recommendation generated</div><div class="summary"><div><span>Total Budget</span><b>${money(r.total_budget)}</b></div><div><span>Remaining</span><b>${money(r.remaining_budget)}</b></div></div>`;const cats=r.budget_breakdown||[];if(cats.length)html+=`<h3>Budget Breakdown</h3><div class="breakdown">${cats.map(c=>`<div><span>${esc(c.category)}</span><b>${money(c.allocation)}</b></div>`).join('')}</div>`;const items=r.items||r.jewelry_recommendations||[];if(items.length)html+=`<h3>Recommendations</h3><div class="rec-list">${items.map(i=>`<article><div><b>${esc(i.name||'Recommendation')}</b><p>${esc(i.description||'')}</p></div><strong>${money(i.estimated_price)}</strong><div class="links">${Object.entries(i.shopping_links||{}).map(([k,v])=>`<a target="_blank" rel="noopener" href="${v}">${k}</a>`).join('')}</div></article>`).join('')}</div>`;if(r.additional_suggestions?.length||r.styling_tips?.length){const tips=r.additional_suggestions||r.styling_tips;html+=`<h3>Tips</h3><ul>${tips.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`}html+=`<a class="btn" href="/recommendation/${r.recommendation_id}">Open Full Recommendation</a>`;return html}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function plannerForm(id,url,kind){document.getElementById(id).addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,r=f.querySelector('.result');r.innerHTML='<div class="loading">Generating your plan…</div>';try{let options={method:'POST'};if(kind==='jewelry'){options.body=new FormData(f)}else{const raw=Object.fromEntries(new FormData(f));if(kind==='home')raw.rooms=raw.rooms.split(',').map(x=>x.trim()).filter(Boolean);if(kind==='party')raw.needs=raw.needs.split(',').map(x=>x.trim()).filter(Boolean);for(const k of ['total_budget','num_lights','num_fans','num_furniture','num_dining_tables','num_guests'])if(k in raw)raw[k]=Number(raw[k]);options.headers={'Content-Type':'application/json'};options.body=JSON.stringify(raw)}const data=await api(url,options);r.innerHTML=renderResult(data)}catch(x){r.innerHTML=`<div class="error">${esc(x.message)}</div>`}})}
async function loadRecent(){try{const d=await api('/api/recommendation-history');const el=document.getElementById('recent');el.innerHTML=d.slice(0,3).map(x=>`<a class="history-card" href="/recommendation/${x.id}"><small>${x.type}</small><h3>${money(x.summary.budget)}</h3><p>${new Date(x.created_at).toLocaleString()}</p></a>`).join('')||'<div class="empty">No recommendations yet.</div>'}catch(e){}}
async function loadHistory(){try{const d=await api('/api/recommendation-history');const el=document.getElementById('historyList');el.innerHTML=d.map(x=>`<a class="history-card" href="/recommendation/${x.id}"><small>${x.type}</small><h3>Budget ${money(x.summary.budget)}</h3><p>Remaining ${money(x.summary.remaining)}</p><p>${new Date(x.created_at).toLocaleString()}</p></a>`).join('')||'<div class="empty">No recommendations yet.</div>'}catch(e){document.getElementById('historyList').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
